server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/devdb
    username: ups
    password: ups123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
